service: cors-rust
configValidationMode: off
provider:
  name: scaleway
  runtime: rust179

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

functions:
  cors-permissive:
    handler: handler_with_cors
