service: nginx-hello
configValidationMode: off
provider:
  name: scaleway

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

custom:
  containers:
    first:
      registryImage: nginx
      port: 80
      memoryLimit: 256
      cpuLimit: 140
