
.PHONY: tf-init
tf-init:
	cd terraform && terraform init

.PHONY: tf-plan
tf-plan:
	cd terraform && terraform plan

.PHONY: tf-apply
tf-apply:
	cd terraform && terraform apply -auto-approve

.PHONY: tf-destroy
tf-destroy:
	cd terraform && terraform destroy
