service: scaleway-container

provider:
  name: scaleway

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!.idea/**'

custom:
  containers:
    first:
      directory: app
      events:
        - schedule:
            rate: '0 * * * *'