service: python-deps-example
configValidationMode: off

provider:
  name: scaleway
  runtime: python310

plugins:
  - serverless-scaleway-functions
  - serverless-python-requirements

package:
  patterns:
    - '!node_modules/**'

functions:
  requests:
    handler: handler.handle
