service: python-dependencies-example
configValidationMode: off

provider:
  name: scaleway
  runtime: python310

plugins:
  - serverless-scaleway-functions
  - serverless-python-requirements

package:
  patterns:
    - '!node_modules/**'

functions:
  dependency-example:
    handler: handler.handle

# Custom config needed to handle native charset dependencies pulled in with requests
custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: rg.fr-par.scw.cloud/scwfunctionsruntimes-public/python-dep:3.10
