version: "3"

services:
  data:
    build:
      context: ./data
    depends_on:
      - minio
    environment:
      - ACCESS_KEY=example
      - SECRET_KEY=example-password
      - REGION=foo
      - S3_BUCKET_NAME=mlops
      - S3_URL=http://minio:9000

  training:
    build:
      context: ./training
    depends_on:
      - minio
    environment:
      - ACCESS_KEY=example
      - SECRET_KEY=example-password
      - REGION=foo
      - S3_BUCKET_NAME=mlops
      - S3_URL=http://minio:9000

  inference:
    build:
      context: ./inference
    ports:
      - 8080:80
    depends_on:
      - minio
    environment:
      - ACCESS_KEY=example
      - SECRET_KEY=example-password
      - REGION=foo
      - S3_BUCKET_NAME=mlops
      - S3_URL=http://minio:9000

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio_storage:/data
    environment:
      - MINIO_ROOT_USER=example
      - MINIO_ROOT_PASSWORD=example-password
    entrypoint: sh
    command: -c 'mkdir -p /data/mlops && /usr/bin/minio server /data'

volumes:
  minio_storage: {}
