service: go-hello-world
configValidationMode: off
provider:
  name: scaleway
  runtime: go121

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

functions:
  hello-go:
    handler: "Handle"
