service: rust-examples
configValidationMode: off
useDotenv: true
provider:
  name: scaleway
  runtime: rust185

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - "!target/**"
    - "!www/**"
    - "!training/**"
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

functions:
  main:
    handler: "handler"
    memoryLimit: 1024
    env:
      RUST_LOG: ${env:RUST_LOG, "info"}
      S3_BUCKET: ${env:S3_BUCKET}
      SCW_ACCESS_KEY: ${env:SCW_ACCESS_KEY}
      SCW_DEFAULT_REGION: ${env:SCW_DEFAULT_REGION, "fr-par"}
    secret:
      SCW_SECRET_KEY: ${env:SCW_SECRET_KEY}
