import os

import asyncio
import nats

MAX_FACTORIAL_REQUESTS = 20

# Credentials file generated by Terraform
NATS_CREDS_FILE = os.environ["NATS_CREDS_FILE"]
NATS_ENDPOINT_URL = "nats://nats.mnq.fr-par.scaleway.com:4222"
SUBJECT_NAME = os.environ["NATS_SUBJECT"]

async def send_nats():
    nc = await nats.connect(NATS_ENDPOINT_URL, user_credentials=NATS_CREDS_FILE)

    print(f"Sending 0..{MAX_FACTORIAL_REQUESTS} factorial requests to {SUBJECT_NAME}...")
    for i in range(MAX_FACTORIAL_REQUESTS):
        await nc.publish(SUBJECT_NAME, f"{i}".encode())

    await nc.close()


if __name__ == "__main__":
    asyncio.run(send_nats())
