import os

import boto3

# Credentials generated by terraform
AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]

MAX_FACTORIAL_REQUESTS = 20

params = {
    "endpoint_url": "http://sqs-sns.mnq.fr-par.scw.cloud",
    "aws_access_key_id": AWS_ACCESS_KEY_ID,
    "aws_secret_access_key": AWS_SECRET_ACCESS_KEY,
    "region_name": "fr-par",
}

client = boto3.client("sqs", **params)
sqs = boto3.resource("sqs", **params)


def main():
    queues = client.list_queues()
    for queue_url in queues["QueueUrls"]:
        queue = sqs.Queue(queue_url)
        for i in range(MAX_FACTORIAL_REQUESTS):
            # See: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs/queue/index.html
            queue.send_message(MessageBody=str(i))


if __name__ == "__main__":
    main()
