service: repository-badge-php
configValidationMode: off
provider:
  name: scaleway
  runtime: php82

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - "!..gitignore"
    - "!.git/**"

functions:
  repository-badge:
    handler: handler.handler
